### ISSUE TITLE
Typo in message when removing only patient

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#100]
Message is currently:
Data for atleast one patient needs to be filled in ! 
(with the extra space before the exclamation mark)
(not getting into the data plural/singular debate)

Thinking about it, the message is odd, as your attempt is not about filling it in, it is about deleting patients. 

Possible alternative:
"Patient cannot be removed, at least one patient is required for the analysis".

![image](https://cloud.githubusercontent.com/assets/13958834/16560971/e897e736-41f6-11e6-9e8f-a5c591df5b9e.png)

**Comment by mkuzak** [comment]
I think, if there is only one patient, there should be no _Remove_ button. Giving user a button just to tell him he cannot use it is not very user friendly.

**Comment by JAvRZ** [comment]
Also a valid point.

**Comment by mkuzak** [comment]
Creating new issue for this #117
