### ISSUE TITLE
The plot is not drawn correctly in Firefox.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#121]
The legend on the right side is cut off.

**Comment by jvdzwaan** [comment]
@mkuzak Not only the plot looks weird in firefox, the input boxes too:

![screenshot from 2016-09-26 16-03-23](https://cloud.githubusercontent.com/assets/4788897/18837095/d4a62c44-8402-11e6-9da8-cdc413d61e70.png)

**Comment by mkuzak** [comment]
this is strange, that should be standard Bootstrap look. Maybe it's the problem again with overriding bootstrap CSS.

**Comment by jvdzwaan** [comment]
The really strange thing is that the age input box looks fine, but the test ones don't

**Comment by mkuzak** [comment]
hm, it looks ok in my Firefox macOS Firefox version 50.0b1

**Comment by jvdzwaan** [comment]
Okay, I have more or less fixed it. In firefox, the table is now slightly unaligned. Can we live with that? 
![screenshot from 2016-09-26 17-19-00](https://cloud.githubusercontent.com/assets/4788897/18840104/bec5b47a-840d-11e6-8db2-92173776a357.png)
