### ISSUE TITLE
Not selecting any tests lets you go to visualisation where R error is displayed

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#127]
The R error is: 
`Error: invalid 'times' argument In call: rep(demos, no.tests)`
 which is neatly provided in little red box.

Solutions might be to enforce selection of tests before submittal to OpenCPU, either at test selection or after data entry.

**Comment by mkuzak** [comment]
there are two behaviours that need to be implemented:
- it should not be possible to go to data input page if no test variables are selected
- it should not be possible to upload data with no test variables filled in

**Comment by mkuzak** [comment]
The code only tests if there are missing values in the input table but not if there are any tests selected.
