### ISSUE TITLE
signin page has test selection on top, that should not be there

### ISSUE THREAD

**Issue by jvdzwaan** [andi-nl/ANDI-frontend#129]

**Comment by jvdzwaan** [comment]
@mkuzak I can't reproduce this one.

It should not be possible, because stuff from the angular app is only displayed when the user is authenticated (see file `accounts/views.py`).

Can you provide more details?

**Comment by mkuzak** [comment]
Can you see it here?
http://andi-app.andi-nlesc.surf-hosted.nl/accounts/signin/

Before logging in there should be no button for `test selection` at the top, right from andi logo.

**Comment by jvdzwaan** [comment]
Oh, you mean the button, not the title...

Why can't the button be there when the user is not logged in? (It's easy to remove, I just don't see the point)

**Comment by mkuzak** [comment]
My point is that this button is not functional there. It does not do anything, because it cannot if you're not logged in.

**Comment by jvdzwaan** [comment]
Fixed, see #124
