### ISSUE TITLE
post error when submitting data with missing values for one of the patients

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#133]
When subset of patients (but not all) have missing values, there is post error. If all patients have missing values for particular variable, there is no error and plot is rendered with this variable missing, which is good.
This is more complicated for plotting in case patients having different subsets of variables.

**Comment by jvdzwaan** [comment]
Oh, this is the same as #155 
Closing this one, because #155 has some additional information :)
