### ISSUE TITLE
make ellipsis plot more readable

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#135]
When patient scores are very far away from normal it is hard to tell which ellipse patient belongs to.
One solution I can come up with would be to draw a _chess board_ in the background.

**Comment by jvdzwaan** [comment]
I don't think a chess board solves everything, because datapoint might be outside the chess board square. Have you considered that possibility?

**Comment by mkuzak** [comment]
Yes we did. If the point is outside of the square it does not make sense to plot it in other square so we should either resize the squares to fit all points or don't plot points falling outside of their squares.
