### ISSUE TITLE
Export svg to pdf with use server side python.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#136]

**Comment by mkuzak** [comment]
Here are the things I've found while shortly researching it:

svglib reportlab
https://gist.github.com/mbostock/6466603
https://docs.djangoproject.com/en/dev/howto/outputting-pdf/#install-reportlab
https://docs.djangoproject.com/en/1.8/howto/outputting-pdf/
http://stackoverflow.com/questions/5835795/generating-pdfs-from-svg-input
https://www.davidfischer.name/2015/08/generating-pdfs-with-and-without-python/

**Comment by jvdzwaan** [comment]
Notes to myself
reportlab needs `python3-dev`
cairosvg needs `libffi-dev`, and python packages lxml tinycss cssselect
