### ISSUE TITLE
Use green colour for normal.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#139]
In line plot use green colour for normal range. Do not use green colour for patients.

**Comment by jvdzwaan** [comment]
Can there be no green for the patients at all? (In other words, should we create a custom color scale (so, not use d3 category10)? Or should I just pick a color green that is sufficiently different from the two greens in d3 category10? 

Can there be more than 10 patients at the same time? (So, should we have a color scale with more than 10 different colors?)

**Comment by mkuzak** [comment]
no green for patients and yes there can be more than 10 patients, but I guess that will make it really hard to make distinguishable colours.
