### ISSUE TITLE
inform user about non unique patient id in more explanatory way

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#14]

**Comment by anandgavai** [comment]
This issue is resolved in the current version.

**Comment by mkuzak** [comment]
@anandgavai current version is HEAD master and and it's not fixed there, it's fixed in the pull request.
Please if your commit messages close the issues, then once pull request is merged issues will be closed.
Do not close issues on unmerged pull requests.

**Comment by anandgavai** [comment]
so when do we plan to merge pull request ?

**Comment by mkuzak** [comment]
once you resolve all the issues we discussed in the pull request.

**Comment by anandgavai** [comment]
Now it is fixed

**Comment by mkuzak** [comment]
Ok, validation works, but we need better, more meaningful feedback than just "duplicate".
I'm renaming this issue to reflect that.

**Comment by Nanouk123** [comment]
You mean the feedback the user gets on having a duplicate needs to be more concrete?

Perhaps: "Not all subjects have a unique ID (_print the conflicting ID_). Please make sure all subjects have a unique ID before uploading your file".

Something like that?

**Comment by mkuzak** [comment]
Yes 👍 sth like that. When I read _duplicate_ I might think I have same patient twice it does not point me to fixing the identifier which is an issue here.

**Comment by Nanouk123** [comment]
I agree, just print the conflicting ID's, its up to the user to figure out whether its an actual duplicate patient or just a duplicate ID number.

**Comment by anandgavai** [comment]
By print @Nanouk123 you mean we show a popup with conflicting id's ?

**Comment by Nanouk123** [comment]
The conflicting ID's should be ideally be displayed in the error message.

"Not all subjects have a unique ID ('Insert conflicting ID's separated by a comma'). Please make sure all subjects have a unique ID before uploading your file"
'
Example:
"Not all subjects have a unique ID (13,1108,6697). Please make sure all subjects have a unique ID before uploading your file"

**Comment by mkuzak** [comment]
closed by PR #57
