### ISSUE TITLE
Represent onesidedness in normal band in line plot

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#140]
Because onesided testing is familiar as an extension/alternative to twosided testing, it is perhaps best visualized on top of the twosided band, as a dashed line. So even if testing is onesided, the green (see other issue for green/gray switch) band will look the same, but the dashed line will indicate the changed significance level. I think most of this can be fixed in normcomp, but I'll have to add one extra parameter in there to indicate the level of the dashed line.

Artistic impression for onesided left testing:
![image](https://cloud.githubusercontent.com/assets/13958834/18750160/4242b406-80da-11e6-9f95-7aa4e9798187.png)

**Comment by mkuzak** [comment]
or instead of using dotted line use two shades of green there

**Comment by mkuzak** [comment]
@JAvRZ @jvdzwaan it looks like this is solved. Do you agree?

**Comment by jvdzwaan** [comment]
Yes
