### ISSUE TITLE
Add on the login page an information to sign up if you haven't yet.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#142]
Sign up link on top right is not visible enough. There should be an information on the page next to login boxes.

**Comment by mkuzak** [comment]
What about adding this sentence.

"To use this website you need to create an account first. If you have not created one yet please follow **sing up** link at the right top of this page."

@JAvRZ  would that work?

**Comment by JAvRZ** [comment]
Little edit:
"To use this website you need to create an account. If you have not yet, please click sign up at the right top of this page."

**Comment by jvdzwaan** [comment]
Why not add a 'sign up' link to the sentence?
