### ISSUE TITLE
In ellipse plot, labels/axes seem wrong way round

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#143]
Not a new issue, but I didn't see it on here. I think the x and y dimensions are switched. I've tried to graph the way I understand the current implementation, and the way I think these are more conventionally plotted (which is flipped I think).

Explanation:
![image](https://cloud.githubusercontent.com/assets/13958834/18787262/5e538fbc-81a2-11e6-8599-c1e46e971686.png)

**Comment by mkuzak** [comment]
Can we close it now? Is this solved by 26470765232d92c5751e0ec9e216fc7c3657439a ?

**Comment by jvdzwaan** [comment]
Yes, I thought I closed it in the git commit, but that didn't work...
