### ISSUE TITLE
Data input table glitch.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#148]
When the input value is out of range the rows in different columns get unaligned. See screenshot below.

![screen shot 2016-09-28 at 13 51 23](https://cloud.githubusercontent.com/assets/208443/18912541/325664b8-8583-11e6-9d8f-e400e8bcc3c8.png)

**Comment by jvdzwaan** [comment]
@mkuzak How are we going to solve this one? Do you want me to put back the original css, or are we going to turn it into a proper table?

**Comment by mkuzak** [comment]
I'm for proper table.

**Comment by jvdzwaan** [comment]
There are still problems with parts of the table being invisible.

**Comment by mkuzak** [comment]
Table has been rewritten, this is not and issue any more.
