### ISSUE TITLE
names for datatables

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#164]
Currently datatables have no description. There should be some short label explaining what they contain. @JAvRZ please provide the text that should be used.

**Comment by JAvRZ** [comment]
I think the consensus was that it should be "Univariate normative comparisons, test for supernormality, 95% confidence interval", 

so "Univariate normative comparisons,", whatever is put into the One tailed or two tailed box in the second tab, whatever is put in the percentage tab, "% confidence interval".

The second one similarly: "Multivariate normative comparisons, test for impairment, 95% confidence interval".

If the tailed and % fields are difficult to integrate, just putting Univariate normative comparisons and Multivariate normative comparisons in big lettering would already be an improvement.
