### ISSUE TITLE
Ellipse drawing parameters are not dependent on normative data version

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#167]
The parameters with which the ellipses are drawn I think come from this file:
ANDI-frontend/static/app/data/ellipseparams.csv
while the test names that are specific to the data version come from this directory.
https://github.com/andi-nl/ANDI-frontend/tree/master/static/app/data/2016-01-14

Both contain test names that are specific to that version, so maybe there should be a separate ellipseparams in every version directory?

**Comment by mkuzak** [comment]
They are now.
