### ISSUE TITLE
Ellipse drawing parameters are not specific to confidence interval selection

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#168]
The ellipses are now always of the same size (95% confidence interval), because they are hardcoded in the ellipseparams.csv like that (68% would be smaller, 99% would be larger).

Possible solutions that I can see:
-Mention this at the top of the page, that these ellipses are always 95%, independent of whether you selected 95%, or 68% or 90% or 99%.
-Make multiple ellipseparams (ellipseparams95.csv, ellipseparams68.csv) and select the correct one (but see #167 )
-Add extra columns to the existing ellipseparams.csv (also affected a bit by #167 )

**Comment by mkuzak** [comment]
It does now.
