### ISSUE TITLE
Different behavior in computing variables for different variables (locking and updating)

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#184]
Behavior is a bit different for different variables.
For AVLT1-5, when you finish typing number 5, the total score is completely locked in and cannot be changed anymore.

For RBMT imm rec, when you finish typing story number 2, you can still edit number 1 and 2. If you do so with the change number buttons next to the number, the total does not update, so the total becomes incongruent with the parts. (For RBMT del rec, the behavior is the same as for AVLT1-5)
![image](https://cloud.githubusercontent.com/assets/13958834/20791039/6571597e-b7bb-11e6-93b3-86b108eaa252.png)

I think the behavior for RBMT imm rec is preferable, aside from the non-updating. But since that only happens when you press the one-up and one-down buttons (which are not crucial), that issue might be solved by removing those buttons?

**Comment by jvdzwaan** [comment]
There was a bug in the code for checking the variables: #183 

I'll look into removing the arrows in the input boxes.

**Comment by jvdzwaan** [comment]
The arrows (called spinners) are something added by the browser. So, disabling them is browser dependent, which is not optimal. Therefore, the problem will be solved by also triggering the validation when the spinners are clicked.

**Comment by JAvRZ** [comment]
This image shows that this issue is back ( I thought it had disappeared as well).
![image](https://cloud.githubusercontent.com/assets/13958834/21314399/363c8328-c5f7-11e6-9763-5e9f374381b9.png)

**Comment by JAvRZ** [comment]
Using tab to navigate, I can no longer reproduce the bug (nor can I with the spinner). So closing once again, thanks.
