### ISSUE TITLE
Search field tree expansion

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#24]
On clicking on the search field the tree should be expanded automatically.

**Comment by mkuzak** [comment]
Can you explain why should the tree expand after clicking on the search field?

**Comment by JAvRZ** [comment]
I think the issue was that if you type in a (partial) name of a variable in the search field, this matches leaf nodes, while you only see root nodes if you did not expand yet. So I think the goal was to see the leaf nodes that you matched (so auto-expand the tree if need be).

**Comment by mkuzak** [comment]
This sometimes works and sometimes not.

**Comment by mkuzak** [comment]
We need more testing on that, because it seams to be quite hard to reproduce.

**Comment by mkuzak** [comment]
This seems to be working now.
