### ISSUE TITLE
change the drop down of normative data

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#25]
we need to remove this feature

**Comment by mkuzak** [comment]
What exactly should be removed?

**Comment by anandgavai** [comment]
As far as I understand It needs to be static. In the new requirement list it is mentioned.

**Comment by Nanouk123** [comment]
It should be standard the latest version. With a small button indicating 'change' so you can analyze with older versions. But we want to demotivate people to do this. Corresponds to #1 on the list

**Comment by mkuzak** [comment]
Need to be tested with more than one set of normative data.

**Comment by mkuzak** [comment]
Now there is a button, but the normative dataset is not rendered.

**Comment by mkuzak** [comment]
Closing that one and creating new issue #88 about displaying the name of the chosen data set.
