### ISSUE TITLE
`Selected tests` should be concatenation of category, long name 1, long name 2, and long name 3

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#26]
Selected test tab1 should now have a concatenation of of ID1 and ID2 long names

**Comment by mkuzak** [comment]
Clarification:
In tab _Test Selection_ tests listed in _Selected Tests_ should be concatenation of ID1 and ID2

**Comment by Nanouk123** [comment]
Id say:

In test _selection tab 1_ (+ on the right _'selected tests'_): Tests should be noted: 'category' +   'long name 1' + 'long name 2' + 'long name 3'. 

In tab 2 (fill out data): Print 'ID1' + 'long name 2' + 'long name 3'

In the results tab (so in the plots and tables), stck to ID1, ID2, ID3. These are the 'shortest possible'. this to save space in the tabs/graphs.
