### ISSUE TITLE
Downloaded template should have testdate and birthdate

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#30]
make this changes in the downloaded template

**Comment by mkuzak** [comment]
we need to test it once it is possible to download the template (after fixing issue #43)

**Comment by anandgavai** [comment]
This is fixed in the current version.

**Comment by mkuzak** [comment]
It will be once the pull request #51 is merged

**Comment by anandgavai** [comment]
this can be closed as I changed the variable names

**Comment by anandgavai** [comment]
We should keep this open as I have not fixed it

**Comment by anandgavai** [comment]
It should not have testdate and birthdate as only Age is compulsory for uploading data

**Comment by anandgavai** [comment]
As per our previous conversation @JAvRZ and @Nanouk123  a clinician will not upload file with testdate and birthdate but will only enter age of the patients. Therefore the downloaded template does not have testdate and birthdate

**Comment by mkuzak** [comment]
Downloaded template should only have age.
