### ISSUE TITLE
change the overall font size of the website

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#36]

**Comment by mkuzak** [comment]
@anandgavai  Any suggestions on what the font size should be?

**Comment by anandgavai** [comment]
I do not know what size of font it should be @Nanouk123 can you comment on it ?

**Comment by Nanouk123** [comment]
I think it should be a scaled size to compensate for resolutions. I usually determine this through trial and error. Ao if you have something for me to evaluate you can forward it to me and ill see if its large enough

**Comment by mkuzak** [comment]
The font size have been increased.
