### ISSUE TITLE
Failure upon alphanumeric patient identifier

### ISSUE THREAD

**Issue by ridderl** [andi-nl/ANDI-frontend#39]
When I entered data with patient identifier "p1", no plot appeared after "submit".
Changing the identifier to an integer ("1"), keeping all other data the same, did succesfully result in a plot.

**Comment by JAvRZ** [comment]
Might have been due to R code, patient IDs were inexplicably forced to be numeric, which gave reproducible errors. New R-code in andi-webservices. Tested with patient ID "John" and I now see correct output once more. (I'm normally not this quick, I must admit).

**Comment by mkuzak** [comment]
@JAvRZ does that mean it's fixed now or not?

**Comment by JAvRZ** [comment]
I cannot be sure, Lars signaled the error using the interface, and I tried to fix the R code that could have been the issue (without breaking anything), but I do not know whether this was sufficient to fix the problem that Lars came across in the interface.

**Comment by mkuzak** [comment]
Ok, we'll have to test it once we have working interface again.

**Comment by anandgavai** [comment]
How would we test this ? for this we need to call teh webservice ?

**Comment by mkuzak** [comment]
On hold, until we have integrated web interface with webservice.

**Comment by mkuzak** [comment]
Could not reproduce that any more with current version. Closing.
