### ISSUE TITLE
It is possible to remove second, third and so on patient but not the first.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#40]
I don't understand why the distinction? I think it's more consistent if you can remove all patients.

**Comment by Nanouk123** [comment]
I'm not sure either @JAvRZ ? 

I think in general patients should be removable. So if you upload data from the excelsheet into the portal you will get a filled-out template. But perhaps you want to remove all data for the 4th patient. You should be able by clicking 'x' in the corner to delete that row of scores?

But that would also mean that I should be able to delete the first patient If I wanted to. So the distinction to me does not make sense right away.

**Comment by anandgavai** [comment]
@Nanouk123 @JAvRZ  from our discussion last time Hilde requested to have atleast 1 patient column available. But certainly it is not restricted, if you wish we can remove the first patient too ?

**Comment by Nanouk123** [comment]
This is not the same issue.  Yes you should always have one patient to analyze.  However this shouldn't have to be patient 1. So if I add data from patient 1 patient 2 and patient 3. I should be able to delete patient 1 and analyze data from patient 2 and 3

**Comment by anandgavai** [comment]
Yes makes sense!

**Comment by mkuzak** [comment]
Now it is possible to delete any patient as long as it's not the last one.
