### ISSUE TITLE
Remove toggles and add introductory text in tab 1 tab 2

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#46]
Toggles _Do you want to type in data_ and _Do you want to upload file_ should be removed

**Comment by anandgavai** [comment]
@Nanouk123 if this feature is removed how can clinicians know if this was meant for manual addition or upload the data ?

**Comment by Nanouk123** [comment]
Because we write an instruction on top of the page. So we write 'on this page you can add the data of your patient(s). You can either upload data from an external .csv/xls etc. file by clicking 'download template' and filling out  and reuploading the template. Or you can add data per patient in the form below'. 

Something like that.

**Comment by anandgavai** [comment]
what if a clinicians adds data manually and at the same time uploads a data file ? would it be an integrated sheet than ?

**Comment by Nanouk123** [comment]
Yes. So in theory you could upload your excel file which is then filled out in your sheet on the website. You could also add extra patients on that sheet.
So if I upload data for 10 people but have an extra person not in my excel, I should be able to add data for that patient as well (by clicking 'add patient') after my excel file has been imported.

Though honestly, I don't think this will happen often.

**Comment by anandgavai** [comment]
Alright ! This means the Requirement #12 will not be applicable no more.

**Comment by anandgavai** [comment]
toggles have been removed but we should keep it open for now

**Comment by mkuzak** [comment]
why should we keep it open?

**Comment by anandgavai** [comment]
Once I will adapt the text on 1st and 2nd tab we can close this issue

**Comment by anandgavai** [comment]
We can close this issue now now

**Comment by mkuzak** [comment]
After you make a pull request and I merge it.
