### ISSUE TITLE
Selection bug

### ISSUE THREAD

**Issue by ridderl** [andi-nl/ANDI-frontend#67]
I selected all memory tests and then deselected the RBMT test
After pressing Next still all tests (including RBMT) are in the table

**Comment by anandgavai** [comment]
Alright thanks for pointing it out !

**Comment by mkuzak** [comment]
@ridderl can you confirm if this now works, in cloud instance? If it's still an issue, please reopen it.

**Comment by ridderl** [comment]
Yes, it works now. Thanks
