### ISSUE TITLE
No validation of uniqueness of patient id's in uploaded template.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#71]
When uploading filled in template, patients can have same id's this does not get validated and ends up like that in the table.

**Comment by anandgavai** [comment]
@mkuzak do you mind testing this functionality again ? and if you agree please close it.

**Comment by mkuzak** [comment]
@anandgavai it still does not complain when uploading file with two patients with id: 0 or 'a' or 55, those the ones I tested.
