### ISSUE TITLE
Template download should show up after some tests are selected.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#73]
As explained by @Nanouk123 [here](https://github.com/andi-nl/andi/issues/18#issuecomment-224584775) and I agree with her, having a template download button available when no tests are selected may lead to people trying to use it to download empty template. The solution would be to either disable the button or not show up at all when no tests are selected, show/enable only after some tests are selected.

**Comment by anandgavai** [comment]
Alright thanks

**Comment by mkuzak** [comment]
The button now appears after selecting tests. Looks ok.
