### ISSUE TITLE
Date picker does not work poperly.

### ISSUE THREAD

**Issue by Nanouk123** [andi-nl/ANDI-frontend#75]
Requirement 22:

In my browser (chrome but perhaps old) I don't get the pre-printed dd/mm/yyyy in the box (yet).
Also theres no icon for the calendar which I'd like. Now if I click it it pops up (for all patients, also the ones which I've already given an age which makes the screen look very messy).

So Id like a small calendar icon next to the field. If you click that, than the calendar pops up for that patient only. I will try to find an example on a website for you.
![calendar](https://cloud.githubusercontent.com/assets/6817467/15905608/c4f136a2-2db5-11e6-877e-89aa2ed051de.png)

**Comment by mkuzak** [comment]
Fixed for me. @Nanouk123 can you test in your browser and close an issue if you think it's closed?

**Comment by Nanouk123** [comment]
Yes this works I dont get the tripple pop up anymore.
It does not yet show me how to fill out the date (seems to be with a dash - so 09-07-1987) Which is fine but Id print it behind birthdate (dd-mm-jjjj) so that people who want to type it in can. / doesn't work it seems (again dash is perfectly fine but should be indicated somewhere).

**Comment by Nanouk123** [comment]
- if I leave it with / (so for example I typed 09/07/1987) he will automatically take todays date (4-7-2016). 
  So indicating it should be dash is needed else you don't get the right age calculated.
  ![example](https://cloud.githubusercontent.com/assets/6817467/16554326/6609d4dc-41ce-11e6-9e10-877def550c72.png)

**Comment by JAvRZ** [comment]
Since the dates will no longer be selected (either via date picker or manually) because dates are more privacy-sensitive, I'll close this one as it seems redundant.
