### ISSUE TITLE
Dialog window used to specify missing valus should have better explanation.

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#79]
Provide information message to the user

**Comment by mkuzak** [comment]
What is "file modal dialog"? Can you explain this? What kind of information do you want to provide?

**Comment by anandgavai** [comment]
The file modal dialog is the popup that provides clinicians the possibility to indicate missing values. I have changed the message to make it a bit more clear the purpose of this dialog. Offcourse @Nanouk123  would prrovide a better message later.

**Comment by Nanouk123** [comment]
"Please specify which value(s) is used for missing data. If no value for missing data is used (blank space) you can lave this empty. If you have used multiple values for missing data (e.g. 999 as well as 888) you can define multiple values by separating them by comma (e.g. 999,888)."

How is this? and is it correct (will we use comma separated??)

**Comment by anandgavai** [comment]
yes it is comma separated

**Comment by mkuzak** [comment]
Aren't commas decimal separators now? If so we cannot use them to separate numbers.

**Comment by mkuzak** [comment]
Let's make them semicolon separated if everyone agrees on that.

**Comment by JAvRZ** [comment]
Sounds fine to me.
