### ISSUE TITLE
The downloaded template cannot be uploaded

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#80]
The template downloaded from the website after being filled in by the clinician cannot be uploaded back

**Comment by mkuzak** [comment]
@anandgavai 
This is not true, I can upload filled in template.

**Comment by anandgavai** [comment]
Actually there is a small bug in the script which I need to get it sorted out.

**Comment by mkuzak** [comment]
Can you explain it and update the title of this issue, so that it reflects the problem?

**Comment by anandgavai** [comment]
Same as issue #71
