### ISSUE TITLE
After uplading data, button for upload disepears.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#81]
When I upload data, I'm redirected to tab two, when I go back to tab one, upload button is gone and I cannot upload more data.

**Comment by anandgavai** [comment]
yes this is expected behaviour !

**Comment by mkuzak** [comment]
why?

**Comment by anandgavai** [comment]
this is to prevent user from uploading new data, I can make the upload available again if @Nanouk123 likes ?

**Comment by mkuzak** [comment]
@Nanouk123 @JAvRZ  was it ever a requirement? What is the logic behind not allowing to upload multiple data files?

**Comment by JAvRZ** [comment]
I do not recognize it as a requirement, so I'm unsure about the logic. I think that the risk that the user does no longer know what file he is working with is very small. So I would not dynamically remove the button myself.

**Comment by anandgavai** [comment]
@JAvRZ some questions 
what should be the behaviour if the user uploads the same file with different values again ?

**Comment by mkuzak** [comment]
If the patient id is the same, data should be overwritten, otherwise it's different patient.

**Comment by JAvRZ** [comment]
I am not sure whether I would expect that behavior (I think I would expect: New file means new data, so overrides everything I have done so far). But I do like what you are saying Mateusz, that you can keep uploading patient files for different patients one by one (or if you want, overwrite one of the patients by entering the same ID). So I would think that would be better than what a cynical user like myself would expect.

**Comment by anandgavai** [comment]
@JAvRZ @Nanouk123 can add this to our new requirement list ?

**Comment by mkuzak** [comment]
I would make it an issue, it's not really a requirement.
