### ISSUE TITLE
Missing values are not removed for last patient

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#94]
If the values are outside the range (like 99999), this prohibits the user from going to the output as well. Screenshot should make it clear enough.

![image](https://cloud.githubusercontent.com/assets/13958834/16555209/c883558e-41d3-11e6-9298-06636b9244c4.png)

**Comment by JAvRZ** [comment]
I think this issue has changed. A missing value was introduced, but only for the first patient (I entered 60 as the missing value identifier, with two identical patients)
![image](https://cloud.githubusercontent.com/assets/13958834/16562738/b5aa96f4-41fe-11e6-9d5e-4133f95960aa.png)

However, in the visualisation, the changed variable I think was not made missing, but was replaced by nine 9s. 
![image](https://cloud.githubusercontent.com/assets/13958834/16562871/4d16d854-41ff-11e6-9e16-d957ada09e6d.png)

So really, this issue seems to have split in a, only values for patient 1 are replaced, and b, missing values are not replaced with NA but are replaced with a very high value. This last issue I can probably fix in the andistats normcomp. Shall I, or is it better fixed before the opencpu/R step?

**Comment by mkuzak** [comment]
@JAvRZ wasn't the agreement that opencpu/R expects 999999999 instead of missing values?

**Comment by JAvRZ** [comment]
@mkuzak Okay, I changed the normcomp function to interpret 9 9's as NA's (and added a bit of much required functionality that you make multivariate comparisons with all scores not NA (one NA doesn't invalidate the whole multivariate procedure)). I'll wait with closing this issue, as I'm still not sure whether the website changes all "missing values" to 999999999, and not only for patient 1 (and of course the vm doesn't run this new normcomp just yet).

**Comment by mkuzak** [comment]
Update. Current status is that when there are missing values present but plots are not rendered. There is no error in the console.

**Comment by mkuzak** [comment]
The table has been rewritten. This is not an issue any more.
