### ISSUE TITLE
Onesided tests give strange y-axes. 

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#95]
Onetailed left
![onetailedleft](https://cloud.githubusercontent.com/assets/13958834/16556134/745efcb0-41d8-11e6-847f-1fab89bdf4ff.png)

Onetailed right
![onetailedright](https://cloud.githubusercontent.com/assets/13958834/16556133/7458c19c-41d8-11e6-915a-1141911e37f0.png)

Even if the scale is changed to more realistic values (like 3 instead of 100), the scale can maybe still better be like the twosided plot. It seems like the values in the non-expected direction are either constrained to 0, or would fall off the plot. (Visualizing onesidedness I find tricky as well btw).

As a comparison, twosided looks okay.
![twosided](https://cloud.githubusercontent.com/assets/13958834/16556186/bf509012-41d8-11e6-917f-10b15b89ca46.png)

The p-values for the univariate t-tests seem to not be affected by sidedness, but that is an andistats issue, so I'll create an issue there.

**Comment by jvdzwaan** [comment]
Will be addressed in #140

**Comment by mkuzak** [comment]
I guess we can close it in that case.
