### ISSUE TITLE
When age is < 0, the dates are required (but deactivated)

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#97]
![image](https://cloud.githubusercontent.com/assets/13958834/16557289/34f01288-41df-11e6-8951-8d0257a9a7dc.png)

I cannot quite find out how to precisely replicate this, but when I try to change age back to something normal, I have twice found it to be locked to age = 0 (and all keyboard input and arrow button input is interpreted as 0).
![reallybrokenit age 0](https://cloud.githubusercontent.com/assets/13958834/16557370/a182cd32-41df-11e6-8314-48602d3bbc23.png)

**Comment by mkuzak** [comment]
Now when entering negative age, the template complains.
