### ISSUE TITLE
Confidence interval becomes wider instead of narrower when going from 95 to 68

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/ANDI-frontend#98]
When I saw this I thought it must be a andistats issue, as I think the inneredge and outeredge come from there. But running normcomp on a 68 testjson, I get "inneredge": -0.9947, "outeredge": 0.9947,
95% interval (about -1.96 to 1.96, as expected)
![95interval](https://cloud.githubusercontent.com/assets/13958834/16559479/68d7fb98-41ed-11e6-866c-ed91e67257f4.png)

68% interval (about -2.5, 2.5, expected about -1, 1)
![68interval](https://cloud.githubusercontent.com/assets/13958834/16559480/6b175084-41ed-11e6-956c-52e934243da1.png)

Maybe the labeling of the inputs in the checkbox is different from what is sent to the normcomp function (the inputs in the checkbox are in a strange order anyway). (a 99% interval would correspond to -2.5781 - 2.5781 according to the normcomp run locally).

**Comment by JAvRZ** [comment]
I'm a bit afraid to touch the dataentry file, so I won't, but I think I found the source of this bug: `! <option value="99">68</option>.`

**Comment by mkuzak** [comment]
Option value corrected, but the bug needs to be confirmed for new visualisation.

**Comment by jvdzwaan** [comment]
I think this now works correctly. @JAvRZ can you verify this?

**Comment by JAvRZ** [comment]
Yes, tried a few things, looks alright.
